# Generated by Django 6.0.6 on 2026-06-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('staff_dep', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('inc_type', models.CharField(default='Merit-Based Performance Review', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
        migrations.CreateModel(
            name='OtApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('staff_dep', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('ot_type', models.CharField(default='Day Shift', max_length=50)),
                ('ot_date', models.DateField()),
                ('ot_hours', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_message', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('staff_dep', models.CharField(max_length=100)),
                ('staff_position', models.CharField(max_length=100)),
                ('leave_type', models.CharField(default='Annual Leave', max_length=50)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField()),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
        migrations.CreateModel(
            name='DutyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=150)),
                ('duty_date', models.DateField()),
                ('duty_replacement', models.CharField(max_length=150)),
                ('duty_reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_by_name', models.CharField(default='System Administrator', max_length=150)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.staffprofile', to_field='staff_id')),
            ],
        ),
    ]
