# Generated by Django 6.0.6 on 2026-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('author', models.CharField(default='Corx', max_length=100)),
                ('image', models.CharField(default='https://www.corx.ae/wp-content/uploads/placeholder.jpg', max_length=500)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('eyebrow', models.CharField(blank=True, default='', max_length=250)),
                ('tagline', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Activity', max_length=100)),
                ('theme_color', models.CharField(default='#08709d', max_length=20)),
                ('floating_badge', models.JSONField(blank=True, default=dict)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
