# Generated by Django 5.0.3 on 2026-07-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blogpost_id_alter_dutyapplication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_file',
            field=models.FileField(blank=True, help_text='Upload a local image file from your computer', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_file',
            field=models.FileField(blank=True, help_text='Upload a local image file from your computer', null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
