# Generated by Django 5.0.3 on 2026-08-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='Activity', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='theme_color',
            field=models.CharField(blank=True, default='#08709d', max_length=20),
        ),
    ]
