# Generated by Django 5.0.3 on 2026-08-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_benefits_title_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits_image_file',
            field=models.FileField(blank=True, help_text='Upload custom image file for Benefits Section', null=True, upload_to='service_images/'),
        ),
    ]
