# Generated by Django 5.0.3 on 2026-08-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_benefits_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='understanding_image_file',
            field=models.FileField(blank=True, help_text='Upload custom illustration for Understanding Section', null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='understanding_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='understanding_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='understanding_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
