# Generated by Django 5.0.3 on 2026-08-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_service_custom_url_path_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Custom SEO & OpenGraph Meta Description for this Blog Post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Custom SEO & OpenGraph Title Tag for this Blog Post', max_length=300),
        ),
    ]
