# Generated by Django 5.0.3 on 2026-08-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_blogpost_meta_description_blogpost_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
