# Generated by Django 6.1 on 2026-08-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_blogpost_category_alter_blogpost_date_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siterobots',
            options={'verbose_name': 'Robots.txt Setting', 'verbose_name_plural': 'Robots.txt Settings'},
        ),
        migrations.AlterField(
            model_name='siterobots',
            name='content',
            field=models.TextField(default='User-agent: *\nDisallow: /admin/\nAllow: /', help_text='Custom robots.txt content for this website. Edit rules directly here.'),
        ),
        migrations.AlterField(
            model_name='siterobots',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robots_config', to='sites.site'),
        ),
    ]
