# Generated by Django 6.1 on 2026-08-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_siterobots_options_alter_siterobots_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nDisallow: /admin/\nAllow: /', help_text="Edit your website's robots.txt rules directly below.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt Setting',
                'verbose_name_plural': 'Robots.txt Setting',
            },
        ),
        migrations.DeleteModel(
            name='SiteRobots',
        ),
    ]
