# Generated by Django 6.1 on 2026-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_robotstxt_delete_siterobots'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text="Edit your website's sitemap.xml XML content directly below.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sitemap.xml Setting',
                'verbose_name_plural': 'Sitemap.xml Setting',
            },
        ),
    ]
