# Generated by Django 6.1 on 2026-08-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_sitemapxml'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Member Profile', 'verbose_name_plural': 'Staff Members Directory'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enrolled Date'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('Home Nursing', 'Home Nursing'), ('Doctor on Call', 'Doctor on Call'), ('IV Therapy', 'IV Therapy'), ('Physiotherapy', 'Physiotherapy & Rehabilitation'), ('Lab Services', 'Diagnostic & Lab Tests'), ('Administration', 'Administration & HR'), ('Operations', 'Medical Operations')], default='Home Nursing', help_text='Primary department or healthcare service unit', max_length=100, verbose_name='Clinical Department'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(help_text='Official medical staff name (e.g. Dr. Sarah Jenkins, RN)', max_length=150, verbose_name='Full Legal Name'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(help_text='Password used by the staff member to log into the frontend Staff Portal at /portal', max_length=128, verbose_name='Portal Access Password'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(help_text='Designation (e.g. Senior DHA Registered Nurse, Consultant Physician)', max_length=100, verbose_name='Job Position / Title'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Medical / Clinical Staff'), ('admin', 'Administrator / Management')], default='staff', help_text="Select 'Medical / Clinical Staff' for staff dashboard, or 'Administrator' for executive dashboard", max_length=20, verbose_name='Access Level / Role'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Unique staff identifier used for Portal login (e.g. STF-101, DOC-202, ADMIN-001)', max_length=50, unique=True, verbose_name='Staff / Employee ID'),
        ),
    ]
