# Generated by Django 6.1 on 2026-08-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Member Profile', 'verbose_name_plural': 'Staff Member Directory'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload official passport size photo of the staff member (e.g., JPG, PNG, WEBP)', null=True, upload_to='staff_photos/', verbose_name='Passport Size Photo'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('Home Nursing', 'Home Nursing'), ('Doctor on Call', 'Doctor on Call'), ('IV Therapy', 'IV Therapy'), ('Physiotherapy', 'Physiotherapy & Rehabilitation'), ('Lab Services', 'Diagnostic & Lab Tests'), ('Administration', 'Administration & HR'), ('Operations', 'Medical Operations')], default='Home Nursing', help_text='Clinical or administrative department', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='full_name',
            field=models.CharField(help_text='Full legal name of the staff member (e.g. Dr. Sarah Jenkins, RN)', max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(help_text='Password for Portal access at /portal', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(help_text='Official designation / job position (e.g. Senior DHA Registered Nurse, Consultant Physician)', max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Medical / Clinical Staff'), ('admin', 'Administrator / Management')], default='staff', help_text="Select 'Medical / Clinical Staff' for staff dashboard, or 'Administrator' for management dashboard", max_length=20, verbose_name='Role / Access Level'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(db_index=True, help_text='Username / ID used by the staff member to log in to the portal (e.g. STF-101, DOC-202, ADMIN-001)', max_length=50, unique=True, verbose_name='Username / ID (Portal Login)'),
        ),
    ]
