# Generated by Django 6.1 on 2026-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_staffprofile_options_staffprofile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Clinical or administrative department of your choice (e.g. Home Nursing, Doctor on Call, HR, Operations, etc.)', max_length=100, verbose_name='Department'),
        ),
    ]
