# Generated by Django 6.1 on 2026-08-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_staffprofile_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Notice & Announcement', 'verbose_name_plural': 'Notices & Announcements'},
        ),
        migrations.RemoveField(
            model_name='noticeapplication',
            name='notice_message',
        ),
        migrations.RemoveField(
            model_name='noticeapplication',
            name='notice_title',
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='content',
            field=models.TextField(default='', help_text='Detailed description and announcement information for staff members', verbose_name='Notice Content'),
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='priority',
            field=models.CharField(choices=[('normal', '🟢 Normal Notice'), ('important', '🟡 Important Announcement'), ('urgent', '🔴 Urgent / High Priority')], default='normal', max_length=20, verbose_name='Urgency / Priority'),
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='selected_staff',
            field=models.ManyToManyField(blank=True, help_text='Choose one or more staff members who should receive this notice.', related_name='received_notices', to='api.staffprofile', verbose_name='Select Specific Staff Members'),
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='target_audience',
            field=models.CharField(choices=[('all', '📢 Broadcast to All Staff Members'), ('specific_staff', '👤 Select Specific Staff Members'), ('specific_dept', '🏢 Select by Department')], default='all', help_text='Select whether to send this notice to all staff, specific individuals, or a department.', max_length=30, verbose_name='Send Notice To'),
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='target_department',
            field=models.CharField(blank=True, default='', help_text='Enter department name (e.g. Home Nursing, Doctor on Call, HR) if sending by department.', max_length=100, verbose_name='Target Department'),
        ),
        migrations.AddField(
            model_name='noticeapplication',
            name='title',
            field=models.CharField(default='Official Notice', help_text='Enter the headline / subject of the notice (e.g. Mandatory Clinical Meeting, Holiday Schedule, Shift Update)', max_length=250, verbose_name='Notice Title'),
        ),
        migrations.AlterField(
            model_name='noticeapplication',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='api.staffprofile', to_field='staff_id', verbose_name='Issued By'),
        ),
        migrations.AlterField(
            model_name='noticeapplication',
            name='staff_name',
            field=models.CharField(blank=True, default='Administration / HR', max_length=150, verbose_name='Issuer Name'),
        ),
        migrations.AlterField(
            model_name='noticeapplication',
            name='status',
            field=models.CharField(default='Published', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='noticeapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date & Time'),
        ),
    ]
