# Generated by Django 6.1 on 2026-09-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_noticeapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Monthly Salary Slip & Appraisal', 'verbose_name_plural': 'Monthly Salary Slips & Appraisals'},
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Basic Salary (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Deductions (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Housing Allowance (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='issued_by',
            field=models.CharField(default='Management / HR', max_length=150, verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Net Take-Home Salary (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Other Allowance / Bonus (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Overtime Pay (AED)'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer (WPS)', 'Bank Transfer (WPS)'), ('Direct Bank Wire', 'Direct Bank Wire'), ('Company Cheque', 'Company Cheque'), ('Cash in Hand', 'Cash in Hand'), ('Exchange House', 'Exchange House')], default='Bank Transfer (WPS)', max_length=100, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='Remarks / Notes'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='salary_month',
            field=models.CharField(blank=True, default='', help_text='e.g. August 2026 or 2026-08', max_length=100, verbose_name='Salary Month / Period'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='slip_document',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/', verbose_name='Attachment / Payslip Document'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Transport Allowance (AED)'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='inc_type',
            field=models.CharField(default='Monthly Salary Slip', max_length=100, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='api.staffprofile', to_field='staff_id', verbose_name='Staff Member'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff_dep',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff_name',
            field=models.CharField(max_length=150, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff_position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Position / Designation'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued & Sent to Staff'), ('Paid', 'Paid & Settled'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Issued', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Issued Date & Time'),
        ),
    ]
