# Generated by Django 6.1 on 2026-09-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_salaryapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Monthly Salary Slip', 'verbose_name_plural': 'Monthly Salary Slips'},
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='housing_allowance',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='inc_type',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='overtime_amount',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='salary_month',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='slip_document',
        ),
        migrations.RemoveField(
            model_name='salaryapplication',
            name='transport_allowance',
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Enter salary slip description or remarks for the staff', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='salaryapplication',
            name='image',
            field=models.FileField(blank=True, help_text='Upload official salary slip image or document', null=True, upload_to='salary_slips/', verbose_name='Salary Slip Image / Document'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='api.staffprofile', to_field='staff_id', verbose_name='Choose Staff Member'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Staff Name'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='staff_position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='status',
            field=models.CharField(default='Issued', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salaryapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date & Time'),
        ),
    ]
