# Generated by Django 6.1 on 2026-09-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_salaryapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Full name of the assigned driver', max_length=150, verbose_name='Driver / Chauffeur Name')),
                ('driver_phone', models.CharField(blank=True, default='', help_text='Mobile / WhatsApp number of the driver', max_length=50, verbose_name='Driver Contact Number')),
                ('vehicle_info', models.CharField(blank=True, default='', help_text='e.g. Toyota HiAce - DXB 45921 or Mercedes Vito', max_length=100, verbose_name='Vehicle & Plate No.')),
                ('patient_name', models.CharField(blank=True, default='', help_text='Name of the patient, doctor, or client for this trip', max_length=150, verbose_name='Patient / Client / Passenger Name')),
                ('patient_phone', models.CharField(blank=True, default='', help_text='Contact number for passenger / patient', max_length=50, verbose_name='Passenger Contact Number')),
                ('pickup_location', models.CharField(help_text='Starting address or pickup point', max_length=255, verbose_name='Pickup Location')),
                ('drop_location', models.CharField(help_text='Destination address or clinic / hospital location', max_length=255, verbose_name='Drop-off Destination')),
                ('schedule_date', models.DateField(help_text='Date of the scheduled trip', verbose_name='Schedule Date')),
                ('pickup_time', models.CharField(blank=True, default='', help_text='e.g. 09:30 AM or 14:00', max_length=50, verbose_name='Pickup Time')),
                ('drop_time', models.CharField(blank=True, default='', help_text='Estimated completion time (optional)', max_length=50, verbose_name='Drop-off / Return Time')),
                ('trip_type', models.CharField(choices=[('Patient Transport', 'Patient Transport'), ('Doctor / Nurse Home Visit', 'Doctor / Nurse Home Visit'), ('Lab Sample Pickup', 'Lab Sample Pickup'), ('Equipment Delivery', 'Equipment Delivery'), ('Staff Commute', 'Staff Commute'), ('Emergency Transfer', 'Emergency Transfer'), ('Other', 'Other')], default='Patient Transport', max_length=50, verbose_name='Trip Type')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=30, verbose_name='Trip Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Any special instructions, patient medical requirements, or gate passes', verbose_name='Notes / Special Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('driver', models.ForeignKey(blank=True, help_text='Select the registered driver / staff member (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_schedules', to='api.staffprofile', to_field='staff_id', verbose_name='Assigned Driver / Staff Member')),
            ],
            options={
                'verbose_name': 'Driver Schedule',
                'verbose_name_plural': 'Driver Schedules',
                'ordering': ['-schedule_date', '-created_at'],
            },
        ),
    ]
