# Generated by Django 6.1 on 2026-09-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_driverschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverschedule',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Select the registered driver or staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_schedules', to='api.staffprofile', to_field='staff_id', verbose_name='Assigned Driver / Staff Member'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='driver_name',
            field=models.CharField(blank=True, default='', help_text='Automatically set from selected staff member', max_length=150, verbose_name='Driver / Staff Name'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='vehicle_info',
            field=models.CharField(blank=True, default='', help_text='e.g. DXB 45921 or Toyota HiAce - DXB 45921', max_length=100, verbose_name='Vehicle Plate No.'),
        ),
    ]
