# Generated by Django 6.1 on 2026-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_driverschedule_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverschedule',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='driverschedule',
            name='patient_phone',
        ),
    ]
