# Generated by Django 6.1 on 2026-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_driverschedule_patient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverschedule',
            name='trip_type',
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='drop_location',
            field=models.CharField(help_text='Destination address / arrival location', max_length=255, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='drop_time',
            field=models.CharField(blank=True, default='', help_text='Expected time of arrival at destination (e.g. 10:30 AM)', max_length=50, verbose_name='Destination Time'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Any special instructions or route notes', verbose_name='Notes / Special Instructions'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='pickup_location',
            field=models.CharField(help_text='Starting address or source location', max_length=255, verbose_name='Source (Starting Location)'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='pickup_time',
            field=models.CharField(blank=True, default='', help_text='Time of departure from source (e.g. 09:30 AM)', max_length=50, verbose_name='Source / Starting Time'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=30, verbose_name='Status'),
        ),
    ]
