# Generated by Django 6.1 on 2026-09-05 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_driverschedule_trip_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverschedule',
            name='drop_location',
            field=models.CharField(blank=True, default='', help_text='Primary destination address or summary arrival location', max_length=255, verbose_name='Primary Destination'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='drop_time',
            field=models.CharField(blank=True, default='', help_text='Expected time of arrival at destination (e.g. 10:30 AM)', max_length=50, verbose_name='Primary Destination Time'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='pickup_location',
            field=models.CharField(blank=True, default='', help_text='Primary starting address or summary source location', max_length=255, verbose_name='Primary Source (Starting Location)'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='pickup_time',
            field=models.CharField(blank=True, default='', help_text='Time of departure from source (e.g. 09:30 AM)', max_length=50, verbose_name='Primary Source Time'),
        ),
        migrations.CreateModel(
            name='DriverRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField(default=1, help_text='Order of this trip stop (e.g. 1, 2, 3...)', verbose_name='Stop # / Sequence')),
                ('source_location', models.CharField(help_text='Starting address or pick-up point', max_length=255, verbose_name='Source (Pick-up Location)')),
                ('source_time', models.CharField(blank=True, default='', help_text='Departure time from source (e.g. 09:30 AM)', max_length=50, verbose_name='Source / Pick-up Time')),
                ('destination_location', models.CharField(help_text='Destination address or drop-off point', max_length=255, verbose_name='Destination (Drop Location)')),
                ('destination_time', models.CharField(blank=True, default='', help_text='Arrival time at destination (e.g. 10:30 AM)', max_length=50, verbose_name='Destination / Drop Time')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=30, verbose_name='Status')),
                ('notes', models.CharField(blank=True, default='', help_text='Special instructions for this specific route stop', max_length=255, verbose_name='Notes / Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='api.driverschedule', verbose_name='Driver Schedule')),
            ],
            options={
                'verbose_name': 'Trip Route / Stop',
                'verbose_name_plural': 'Trip Routes & Stops',
                'ordering': ['stop_order', 'id'],
            },
        ),
    ]
