# Generated by Django 6.1 on 2026-09-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_driverschedule_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroutestop',
            name='staff_passenger',
            field=models.ForeignKey(blank=True, help_text='Select staff member to pick up / drop for this route leg (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stop_passengers', to='api.staffprofile', to_field='staff_id', verbose_name='Staff to Pick Up / Drop'),
        ),
        migrations.AddField(
            model_name='driverroutestop',
            name='staff_passenger_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Passenger / Staff Name'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='staff_passenger',
            field=models.ForeignKey(blank=True, help_text='Select the staff member / nurse / doctor to pick up from source and drop at destination', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_schedules', to='api.staffprofile', to_field='staff_id', verbose_name='Staff to Pick Up / Drop (Passenger)'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='staff_passenger_name',
            field=models.CharField(blank=True, default='', help_text='Automatically set from selected staff member', max_length=150, verbose_name='Staff / Passenger Name'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='staff_passenger_phone',
            field=models.CharField(blank=True, default='', help_text='Mobile / WhatsApp number of the passenger', max_length=50, verbose_name='Passenger Contact Number'),
        ),
    ]
