# Generated by Django 6.1 on 2026-09-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_driverroutestop_staff_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroutestop',
            name='staff_passengers',
            field=models.ManyToManyField(blank=True, help_text='Select one or more staff members to pick up', related_name='route_stop_passengers_multi', to='api.staffprofile', verbose_name='Staff to Pick Up (Passengers)'),
        ),
        migrations.AlterField(
            model_name='driverroutestop',
            name='staff_passenger_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Passenger / Staff Name(s)'),
        ),
    ]
