# Generated by Django 6.1 on 2026-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_driverroutestop_staff_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverroutestop',
            name='staff_dropoffs',
            field=models.ManyToManyField(blank=True, help_text='Select one or more staff members to drop off at destination', related_name='route_stop_dropoffs', to='api.staffprofile', verbose_name='Staff to Drop Off'),
        ),
        migrations.AlterField(
            model_name='driverroutestop',
            name='staff_passengers',
            field=models.ManyToManyField(blank=True, help_text='Select one or more staff members to pick up at source', related_name='route_stop_passengers_multi', to='api.staffprofile', verbose_name='Staff to Pick Up (Passengers)'),
        ),
    ]
