# Generated by Django 6.1 on 2026-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_driverroutestop_staff_dropoffs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Duty Schedule Swap', 'verbose_name_plural': 'Duty Schedule Swaps'},
        ),
        migrations.AddField(
            model_name='dutyapplication',
            name='shift_timing',
            field=models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], default='Day', help_text='Select Shift Timing: Day or Night', max_length=50, verbose_name='Shift Timing'),
        ),
        migrations.AddField(
            model_name='dutyapplication',
            name='shift_type',
            field=models.CharField(choices=[('6-hours', '6 Hours'), ('8-hours', '8 Hours'), ('10-hours', '10 Hours'), ('12-hours', '12 Hours'), ('24-hours', '24 Hours'), ('live-in', 'Live In')], default='8-hours', help_text='Select Shift Duration: 6, 8, 10, 12, 24 Hours or Live In', max_length=50, verbose_name='Shift Type'),
        ),
        migrations.AlterField(
            model_name='dutyapplication',
            name='duty_date',
            field=models.DateField(verbose_name='Scheduled Duty Date'),
        ),
        migrations.AlterField(
            model_name='dutyapplication',
            name='duty_reason',
            field=models.TextField(verbose_name='Reason / Handover Notes'),
        ),
        migrations.AlterField(
            model_name='dutyapplication',
            name='duty_replacement',
            field=models.CharField(max_length=150, verbose_name='Replacement Staff Name'),
        ),
        migrations.AlterField(
            model_name='dutyapplication',
            name='staff_name',
            field=models.CharField(max_length=150, verbose_name='Staff Name'),
        ),
    ]
