# Generated by Django 6.1 on 2026-09-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_dutyapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Detail', 'verbose_name_plural': 'Staff Details'},
        ),
    ]
