# Generated by Django 6.1 on 2026-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_staffprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='schema_markup',
            field=models.TextField(blank=True, default='', help_text="Custom JSON-LD Schema for this Service (e.g. JSON {...} or <script type='application/ld+json'>{...}</script>)", verbose_name='Custom JSON-LD Schema'),
        ),
    ]
