# Generated by Django 6.1 on 2026-09-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_service_schema_markup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Home Page', max_length=250, verbose_name='Page Title')),
                ('meta_title', models.CharField(default='CORX Healthcare: Home Health Care Services in Dubai *24/7', help_text='Custom SEO & OpenGraph Title Tag for the Home Page', max_length=300, verbose_name='Meta Title Tag')),
                ('meta_description', models.TextField(default='Get premium home health care services in Dubai with Corx Healthcare. Book expert doctors and nurses for physiotherapy, IV therapy, lab tests & elder care, available 24/7.', help_text='Custom SEO & OpenGraph Meta Description for the Home Page', verbose_name='Meta Description')),
                ('canonical_url', models.CharField(default='https://corx.ae/', help_text='Canonical URL for search engines (e.g. https://corx.ae/)', max_length=300, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, default='', help_text='Custom OpenGraph Title (leave blank to use Meta Title)', max_length=300, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, default='', help_text='Custom OpenGraph Description (leave blank to use Meta Description)', verbose_name='OG Description')),
                ('og_image', models.CharField(blank=True, default='https://corx.ae/og-image.webp', help_text='Social sharing preview image URL', max_length=500, verbose_name='OG Image URL')),
                ('og_image_file', models.FileField(blank=True, help_text='Upload custom social preview image file from your computer', null=True, upload_to='home_images/', verbose_name='Upload OG Image File')),
                ('hero_title', models.CharField(blank=True, default='Home Healthcare Services in Dubai', max_length=300, verbose_name='Hero Title')),
                ('hero_eyebrow', models.CharField(blank=True, default='24/7 DHA-LICENSED CLINICAL CARE', max_length=250, verbose_name='Hero Eyebrow')),
                ('hero_tagline', models.TextField(blank=True, default='DHA-licensed doctors, nurses, and physiotherapists at your home, hotel, or office in 30-45 minutes.', verbose_name='Hero Tagline / Description')),
                ('schema_markup', models.TextField(blank=True, default='', help_text='Custom JSON-LD Schema (leave empty to use default MedicalBusiness schema)', verbose_name='Custom JSON-LD Schema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
