# Generated by Django 6.1 on 2026-09-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faq_description',
            field=models.TextField(blank=True, default='Find answers to the most common questions about our home healthcare services in Dubai.', help_text='Subheading description displayed below the FAQ section title', verbose_name='FAQ Section Description / Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_eyebrow',
            field=models.CharField(blank=True, default='⊙ Common Questions', help_text='Eyebrow tag above the FAQ section title', max_length=200, verbose_name='FAQ Eyebrow Tag'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(blank=True, default='Frequently Asked Questions', help_text='Main heading for the FAQ section on the home page', max_length=300, verbose_name='FAQ Section Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text="List of questions and answers: [{'q': '...', 'a': '...'}]", verbose_name='FAQ Items List'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_description',
            field=models.TextField(blank=True, default='', help_text='Custom Subheading Description for FAQ Section', verbose_name='FAQ Section Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_title',
            field=models.CharField(blank=True, default='', help_text='Custom Heading for FAQ Section', max_length=300, verbose_name='FAQ Section Title'),
        ),
    ]
