# Generated by Django 6.1 on 2026-09-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_homepage_faq_description_homepage_faq_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='faq_eyebrow',
            field=models.CharField(blank=True, default='Common Questions', help_text='Eyebrow tag above the FAQ section title', max_length=200, verbose_name='FAQ Eyebrow Tag'),
        ),
    ]
