# Generated by Django 6.1 on 2026-10-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_homepage_faq_eyebrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeapplication',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal Notice'), ('important', 'Important Announcement'), ('urgent', 'Urgent / High Priority')], default='normal', max_length=20, verbose_name='Urgency / Priority'),
        ),
        migrations.AlterField(
            model_name='noticeapplication',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Broadcast to All Staff Members'), ('specific_staff', 'Select Specific Staff Members'), ('specific_dept', 'Select by Department')], default='all', help_text='Select whether to send this notice to all staff, specific individuals, or a department.', max_length=30, verbose_name='Send Notice To'),
        ),
    ]
