"""
Django settings for healthcare_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment configuration
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Monkeypatch database version checks to allow older MariaDB versions
from django.db.backends.base.base import BaseDatabaseWrapper
BaseDatabaseWrapper.check_database_version_supported = lambda self: None

from django.db.backends.mysql.features import DatabaseFeatures
DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)

# Try installing PyMySQL as MySQLdb for Linux / Hostinger compatibility
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-$52mo)@jul!^*)h-x0tph%0#8+e0xxq%b#3o0572av%l9gt2en')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'healthcare_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'healthcare_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_engine = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
if 'mysql' in db_engine:
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': os.getenv('DB_NAME', 'complete_healthcare'),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() in ('true', '1', 't')
raw_cors = os.getenv('CORS_ALLOWED_ORIGINS', 'https://corx.ae,https://www.corx.ae,https://api.corx.ae,https://www.api.corx.ae,http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173')
CORS_ALLOWED_ORIGINS = [
    "https://corx.ae",
    "https://www.corx.ae",
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
]

JAZZMIN_SETTINGS = {
    "site_title": "CORx Healthcare Operations & Admin",
    "site_header": "CORx Healthcare Admin",
    "site_brand": "CORx Healthcare",
    "site_logo": "api/logo.webp",
    "site_icon": "api/logo.webp",
    "welcome_sign": "Welcome to CORx Healthcare Executive Operations & Services Hub",
    "copyright": "CORx Healthcare Dubai",
    "user_avatar": None,
    "custom_css": "api/css/custom_admin.css",
    "custom_js": "api/js/custom_admin_tabs.js",
    "topmenu_links": [
        {"name": "Home Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Services Manager", "url": "/admin/api/service/", "permissions": ["api.view_service"]},
        {"name": "Staff Directory", "url": "/admin/api/staffprofile/", "permissions": ["api.view_staffprofile"]},
        {"name": "Blog Posts", "url": "/admin/api/blogpost/", "permissions": ["api.view_blogpost"]},
        {"name": "React Frontend Dashboard", "url": "/dashboard", "new_window": True},
        {"name": "Live Web App", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["api", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users",
        "api.staffprofile": "fas fa-user-md",
        "api.task": "fas fa-tasks",
        "api.leaveapplication": "fas fa-calendar-times",
        "api.otapplication": "fas fa-user-clock",
        "api.salaryapplication": "fas fa-money-check-alt",
        "api.noticeapplication": "fas fa-bullhorn",
        "api.dutyapplication": "fas fa-exchange-alt",
        "api.blogpost": "fas fa-newspaper",
        "api.service": "fas fa-briefcase-medical",
        "api.teammember": "fas fa-user-nurse",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file-medical",
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-info",
    "accent": "accent-info",
    "navbar": "navbar-info navbar-dark",
    "no_navbar_border": False,
    "navbar_double_row": False,
    "scroller": False,
    "sidebar": "sidebar-dark-info",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_layout": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cerulean",
    "button_classes": {
        "primary": "btn-info",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CONTACT_EMAIL = os.getenv('CONTACT_EMAIL')

# Allow large blog article content to be saved without 500 errors
# Default is 2.5 MB which is too small for rich HTML article content
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800   # 50 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000    # Increase max POST fields limit
